# Generated by Django 2.2.7 on 2020-04-15 02:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Spell',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=60)),
                ('level', models.CharField(choices=[('cantrip', 'Cantrip'), ('1', '1'), ('2', '2'), ('3', '3'), ('4', '4'), ('5', '5'), ('6', '6'), ('7', '7'), ('8', '8'), ('9', '9')], default=0, max_length=12)),
                ('school', models.CharField(choices=[('Abjuration', 'Abjuration'), ('Conjuration', 'Conjuration'), ('Divination', 'Divination'), ('Enchantment', 'Enchantment'), ('Evocation', 'Evocation'), ('Illusion', 'Illusion'), ('Necromancy', 'Necromancy'), ('Transmutation', 'Transmutation')], max_length=20)),
                ('casting_time', models.CharField(max_length=30)),
                ('range', models.CharField(max_length=30)),
                ('components', models.CharField(choices=[('vsm', 'V, S, M'), ('vs', 'V, S'), ('vm', 'V, M'), ('sm', 'S, M'), ('v', 'V'), ('s', 'S'), ('m', 'M')], max_length=10)),
                ('materials', models.CharField(blank=True, max_length=100, null=True)),
                ('duration', models.CharField(max_length=60)),
                ('description', models.TextField()),
            ],
        ),
    ]
